#!/bin/bash


mkdir $1
echo "=============================================================================================="
echo "                                       Quick Nmap Scan                                        "
echo "=============================================================================================="
sudo nmap -Pn -sS -T4 $1 -oN $1/quick_nmap_scan

port=[$(grep open $1/quick_nmap_scan | cut -d" " -f1 | cut -d "/" -f1 | paste -s -d ',')]

echo "=============================================================================================="
echo "                                    Quick Script Nmap Scan                                    "
echo "=============================================================================================="

sudo nmap -Pn -sS -T4 $1 -p$port -A -oN $1/script_nmap_scan

allports=$(grep open $1/quick_nmap_scan | cut -d" " -f1 |cut -d "/" -f1 |paste -s -d ' ')

for i in $(echo "${allports}")
do
	if [ $i = 80 ]
	then
		echo "=================================================================="
		echo "              Nikto Scan is running in background                 "
	    	echo "=================================================================="	
		nikto -Format txt -o $1/nikto_scan.txt -host $1 &
	fi
done

echo "=============================================================================================="
echo "                                      Full Nmap Scan                                          "
echo "=============================================================================================="

sudo nmap -Pn -v -sS -T4 -p- $1 -oN $1/full_nmap_scan

ports=[$(grep open $1/full_nmap_scan | cut -d " " -f1 | cut -d "/" -f1 | paste -s -d ',')]

echo "=============================================================================================="
echo "                                    Full Script  Nmap Scan                                    "
echo "=============================================================================================="

sudo nmap -Pn -sS -T4 -A -p$ports $1 -oN $1/full_script_scan
